"""Add AI analysis usage tracking

Revision ID: a1da0846dfc6
Revises: f9f37d184b0b
Create Date: 2026-01-13 12:28:11.804334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1da0846dfc6'
down_revision: Union[str, Sequence[str], None] = 'f9f37d184b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_analysis_usage_date'), 'ai_analysis_usage', ['date'], unique=False)
    op.create_index(op.f('ix_ai_analysis_usage_id'), 'ai_analysis_usage', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_analysis_usage_id'), table_name='ai_analysis_usage')
    op.drop_index(op.f('ix_ai_analysis_usage_date'), table_name='ai_analysis_usage')
    op.drop_table('ai_analysis_usage')
    # ### end Alembic commands ###
