"""sync models

Revision ID: c2d3ece07f83
Revises: e0db2f1126c3
Create Date: 2026-01-09 20:17:53.897847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c2d3ece07f83'
down_revision: Union[str, Sequence[str], None] = 'e0db2f1126c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ### end Alembic commands ###
